//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace user13.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user13Entities1 : DbContext
    {
        public user13Entities1()
            : base("name=user13Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
        }

        private static user13Entities1 _context;
        public static user13Entities1 GetContext() 
        {
            if (_context == null)
            {
                _context = new user13Entities1();
            }
            return _context;
        }
    
        public DbSet<material_type> material_type { get; set; }
        public DbSet<materials> materials { get; set; }
        public DbSet<product_materials> product_materials { get; set; }
        public DbSet<product_type> product_type { get; set; }
        public DbSet<products> products { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<unit> unit { get; set; }
    }
}
