//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace user13.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class material_type
    {
        public material_type()
        {
            this.materials = new HashSet<materials>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string percent { get; set; }
    
        public virtual ICollection<materials> materials { get; set; }
    }
}
