//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace user13.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public products()
        {
            this.product_materials = new HashSet<product_materials>();
        }
    
        public int id { get; set; }
        public int product_type_id { get; set; }
        public string name { get; set; }
        public int acticul { get; set; }
        public decimal min_price_partners { get; set; }
        public decimal width_roll { get; set; }
    
        public virtual ICollection<product_materials> product_materials { get; set; }
        public virtual product_type product_type { get; set; }

        public string DisplayTypeName
        {
            get
            {
                return $"{this.product_type.name} | {this.name}";
            }
        }

        public string DisplayType
        {
            get
            {
                return $"{this.product_type.name}";
            }
        }
        public string DisplayArticule
        {
            get
            {
                return $"Артикул: {this.acticul}";
            }
        }
        public string DisplayMinPrice
        {
            get
            {
                return $"Мин стоимость: {this.min_price_partners} (р)";
            }
        }
        public string DisplayWidth
        {
            get
            {
                return $"Ширина: {this.width_roll} (м)";
            }
        }

        public string DisplayPrice 
        {
            get 
            {
                return $"Стоимость: {CalculatePrice(this.id).ToString("0.00")} (р)";
            }
        }
        public decimal CalculatePrice(int id) 
        {
            decimal totalPrice = 0;
            foreach (var item in product_materials)
            {
                if (id == item.product_type_id)
                {
                    totalPrice = item.count_material * item.materials.price_unit;
                }
            }

            return totalPrice;
        }
    }
}
