//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace user13.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_type
    {
        public product_type()
        {
            this.products = new HashSet<products>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public decimal coef { get; set; }
    
        public virtual ICollection<products> products { get; set; }
    }
}
